---
# roles/despliegue-dinamico-servicios/tasks/facturascript.yml
#
# FacturaScript necesita de dos contenedores para funcionar:
# - Un contenedor para la base de datos
# - Un contenedor para la aplicación web
#
# --------- Base de datos de FacturaScript ---------
# Crear despliegue para FacturaScript
- name: Crear despliegue para la base de datos de FacturaScript
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "facturascript-db-deployment"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ facturascript_db_name }}"
        template:
          metadata:
            labels:
              app: "{{ facturascript_db_name }}"
          spec:
            containers:
              - name: "{{ facturascript_db_name }}"
                image: "{{ facturascript_db_image }}"
                env:
                  - name: MYSQL_ROOT_PASSWORD
                    value: "{{ facturascript_db_root_password }}"
                  - name: MYSQL_DATABASE
                    value: "{{ facturascript_db_database }}"
                  - name: MYSQL_USER
                    value: "{{ facturascript_db_user }}"
                  - name: MYSQL_PASSWORD
                    value: "{{ facturascript_db_password }}"
                ports:
                  - containerPort: "{{ facturascript_db_port }}"
                volumeMounts:
                  - name: "{{ facturascript_db_volume }}"
                    mountPath: /var/lib/mysql
            volumes:
              - name: "{{ facturascript_db_volume }}"
                persistentVolumeClaim:
                  claimName: "{{ facturascript_db_pvc }}"

# Crear servicio para la base de datos de FacturaScript
- name: Crear servicio para la base de datos de FacturaScript
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "facturascript-db-service"
      spec:
        ports:
          - port: "{{ facturascript_db_port }}"
            targetPort: "{{ facturascript_db_port }}"
        selector:
          app: "{{ facturascript_db_name }}"

# --------- Contenedor de FacturaScript ---------
# Crear despliegue para FacturaScript
- name: Crear despliegue para FacturaScript
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "facturascript-deployment"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ facturascript_app_selector }}"
        template:
          metadata:
            labels:
              app: "{{ facturascript_app_selector }}"
          spec:
            containers:
              - name: "facturascript"
                image: "facturascripts/facturascripts"
                ports:
                  - containerPort: "{{ facturascript_app_port }}"
                volumeMounts:
                  - name: "{{ facturascript_app_volume }}"
                    mountPath: /var/www/html
            volumes:
              - name: "{{ facturascript_app_volume }}"
                persistentVolumeClaim:
                  claimName: "{{ facturascript_app_data_pvc }}"

# Crear servicio para el contenedor de FacturaScript
- name: Crear servicio para FacturaScript
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "facturascript-service"
      spec:
        ports:
          - port: "{{ facturascript_app_port }}"
            targetPort: "{{ facturascript_app_port }}"
        selector:
          app: "{{ facturascript_app_selector }}"

# Crear Ingress para FacturaScript
- name: Crear Ingress para FacturaScript
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "facturascript-ingress"
      spec:
        rules:
          - host: "facturascript.asan-tech.com"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: "facturascript-service"
                      port:
                        number: "{{ facturascript_app_port }}"