#-------------------------------------------------------
# 1. Desplegar la aplicación
#-------------------------------------------------------
- name: Crear despliegue para la aplicación
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ service_name }}-deployment"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ service_name }}"
        template:
          metadata:
            labels:
              app: "{{ service_name }}"
          spec:
            containers:
              - name: "{{ service_name }}"
                image: "{{ app_image }}"
                ports:
                  - containerPort: "{{ app_port }}"

#-------------------------------------------------------
# 2. Crear un servicio para exponer la aplicación
#-------------------------------------------------------
- name: Crear servicio para la aplicación
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ service_name }}-service"
      spec:
        ports:
          - port: "{{ app_port }}"
            targetPort: "{{ app_port }}"
        selector:
          app: "{{ service_name }}"

#-------------------------------------------------------
# 3. Crear un recurso Ingress para enrutar el tráfico
#-------------------------------------------------------
- name: Crear recurso Ingress
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "{{ service_name }}-ingress"
      spec:
        rules:
          - host: "{{ ingress_host }}"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: "{{ service_name }}-service"
                      port:
                        number: 80

#-------------------------------------------------------
# 4. Verificar el estado del despliegue
#-------------------------------------------------------
- name: Verificar el estado del despliegue
  command: kubectl get deployment "{{ service_name }}-deployment"
  register: deployment_status
  changed_when: false

- name: Mostrar el estado del despliegue
  debug:
    msg: "{{ deployment_status.stdout }}"

#-------------------------------------------------------
# 5. Verificar el estado del servicio
#-------------------------------------------------------
- name: Verificar el estado del servicio
  command: kubectl get service "{{ service_name }}-service"
  register: service_status
  changed_when: false

- name: Mostrar el estado del servicio
  debug:
    msg: "{{ service_status.stdout }}"

#-------------------------------------------------------
# 6. Verificar el estado del Ingress
#-------------------------------------------------------
- name: Verificar el estado del Ingress
  command: kubectl get ingress "{{ service_name }}-ingress"
  register: ingress_status
  changed_when: false

- name: Mostrar el estado del Ingress
  debug:
    msg: "{{ ingress_status.stdout }}"

# Ejemplo en PHP
# <?php
# $servicio_elegido = $_POST['servicio'];  // nextcloud o facturascript

# // Ejecutar el playbook de Ansible
# $command = "ansible-playbook /ruta/al/playbook.yml -e 'servicio_elegido=$servicio_elegido'";
# $output = shell_exec($command);

# echo "Playbook ejecutado: " . $output;
# ?>