---
# roles/despliegue-dinamico-servicios/tasks/nextcloud.yml
# Crear despliegue para Nextcloud
- name: Crear despliegue para Nextcloud
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "nextcloud-deployment"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ nextcloud_selector }}"
        template:
          metadata:
            labels:
              app: "{{ nextcloud_selector }}"
          spec:
            containers:
              - name: "nextcloud"
                image: "nextcloud"
                ports:
                  - containerPort: "{{ nextcloud_port }}"
                volumeMounts:
                  - name: "{{ nextcloud_volume }}"
                    mountPath: /var/www/html
            volumes:
              - name: "{{ nextcloud_volume }}"
                persistentVolumeClaim:
                  claimName: "{{ nextcloud_pvc }}"

# Crear servicio para Nextcloud
- name: Crear servicio para Nextcloud
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "nextcloud-service"
      spec:
        ports:
          - port: "{{ nextcloud_port }}"
            targetPort: "{{ nextcloud_port }}"
        selector:
          app: "{{ nextcloud_selector }}"
          
# Crear Ingress para Nextcloud
- name: Crear Ingress para Nextcloud
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "nextcloud-ingress"
      spec:
        rules:
          - host: "nextcloud.asan-tech.com"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: "nextcloud-service"
                      port:
                        number: "{{ nextcloud_port }}"