---
- hosts: all
  become: yes
  tasks:
    - name: Instalar dependencias
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Agregar clave GPG de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Agregar repositorio de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Iniciar y habilitar Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Agregar usuario ansible-user al grupo Docker
      user:
        name: ansible-user
        groups: docker
        append: yes