---
- hosts: all
  become: yes
  tasks:
    - name: Actualizar el sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar Python 3
      apt:
        name: python3
        state: present

    - name: Deshabilitar swap
      shell: |
        swapoff -a
        sed -i '/swap/d' /etc/fstab
      args:
        warn: no  # Ignorar advertencias

    - name: Configurar hostname en el master
      hostname:
        name: master
      when: "'master' in group_names"

    - name: Configurar hostname en los workers
      hostname:
        name: "{{ 'worker' + (play_hosts.index(inventory_hostname) | string) }}"
      when: "'workers' in group_names"

    - name: Configurar /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {{ hostvars['master'].ansible_default_ipv4.address }} master
          {{ hostvars['worker1'].ansible_default_ipv4.address }} worker1
        marker: "# {mark} ANSIBLE MANAGED BLOCK - HOSTS"

    - name: Crear usuario ansible-user
      user:
        name: ansible-user
        groups: sudo
        append: yes
        shell: /bin/bash
        password: "{{ 'password' | password_hash('sha512') }}"

    - name: Configurar acceso SSH sin contraseña
      authorized_key:
        user: ansible-user
        state: present
        key: "{{ lookup('file', '/home/ansible-user/.ssh/id_rsa.pub') }}"