#-------------------------------------------------------
# 1. Copiar el comando de join.
#-------------------------------------------------------
- name: Copiar el archivo al worker
      copy:
        src: /tmp/join_command.sh
        dest: /tmp/join_command.sh
        mode: '0755'

#-------------------------------------------------------
# 2. Unirse al clúster usando kubeadm join
#-------------------------------------------------------
- name: Unirse al clúster de Kubernetes
  command: kubeadm join 192.168.1.12:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash>
  become: true

