apiVersion: v1
kind: ConfigMap
metadata:
  name: web-files
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Contratar Servicio</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <h1>Contratar Servicio</h1>
        <form id="serviceForm">
            <label for="service">Selecciona un servicio:</label>
            <select id="service" name="service">
                <option value="nextcloud">Nextcloud</option>
                <option value="facturascript">FacturaScript</option>
            </select>
            <button type="submit">Contratar</button>
        </form>
        <script src="script.js"></script>
    </body>
    </html>
  style.css: |
    body {
        font-family: Arial, sans-serif;
        margin: 20px;
    }
  script.js: |
    document.getElementById("serviceForm").addEventListener("submit", function (event) {
        event.preventDefault();
        const service = document.getElementById("service").value;
        fetch("backend.php", {
            method: "POST",
            headers: {
                "Content-Type": "application/x-www-form-urlencoded",
            },
            body: `service=${service}`,
        })
            .then((response) => response.text())
            .then((data) => {
                alert("Servicio contratado correctamente.");
                console.log(data);
            })
            .catch((error) => {
                console.error("Error:", error);
            });
    });
  backend.php: |
    <?php
    $servername = "mysql-service";
    $username = "root";
    $password = "password";
    $dbname = "servicios";

    $conn = new mysqli($servername, $username, $password, $dbname);

    if ($conn->connect_error) {
        die("Conexión fallida: " . $conn->connect_error);
    }

    $service = $_POST['service'];

    $sql = "INSERT INTO servicios (nombre) VALUES ('$service')";
    if ($conn->query($sql) === TRUE) {
        echo "Servicio contratado correctamente.";
    } else {
        echo "Error: " . $sql . "<br>" . $conn->error;
    }

    $output = shell_exec("ansible-playbook -i /ruta/al/inventory /ruta/al/playbook-deploy.yml --extra-vars 'servicio=$service'");
    echo "<pre>$output</pre>";

    $conn->close();
    ?>