apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: php:7.4-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-files
          mountPath: /var/www/html
      volumes:
      - name: web-files
        configMap:
          name: web-files