- name: Desplegar servicio en Kubernetes
  command: |
    kubectl apply -f - <<EOF
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ service }}-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: {{ service }}
      template:
        metadata:
          labels:
            app: {{ service }}
        spec:
          containers:
          - name: {{ service }}
            image: {{ service == 'nextcloud' ? 'nextcloud' : 'facturascript/facturascript' }}
            ports:
            - containerPort: 80
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: {{ service }}-service
    spec:
      type: NodePort
      ports:
      - port: 80
        targetPort: 80
      selector:
        app: {{ service }}
    EOF