#-------------------------------------------------------
# Herramientas básicas
#-------------------------------------------------------
- name: Update apt cache
  apt:
    update_cache: yes
    ignore_errors: yes
#-------------------------------------------------------
- name: Install required packages
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3
      - python3-pip
      - gnupg2
      - net-tools
      
    state: present
