
# Crear directorio para los certificados
- name: Crear directorio para los certificados
  file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'

# Generar certificado wildcard autofirmado
- name: Generar certificado wildcard autofirmado
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout {{ cert_dir }}/{{ cert_name }}.key
    -out {{ cert_dir }}/{{ cert_name }}.crt
    -subj "/CN=*.{{ domain }}"
  args:
    creates: "{{ cert_dir }}/{{ cert_name }}.crt"  # No regenerar si ya existe
