- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present